---
title: "dag_iris"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dag_iris}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(scml)
library(torch)
library(luz)
```


```{r}
# Define hierarchy
dag <- matrix(ncol = 2,byrow = TRUE,c(
  4L,5L,
  5L,1L,
  5L,2L,
  4L,3L
)) |> torch_tensor()

# Corresponding ancestor matrix
a <- matrix(c(
  1,0,0,1,1,
  0,1,0,1,1,
  0,0,1,1,0
),3,5,byrow = TRUE)>0

# training data
x <- data.matrix(iris[1:4])
y <- a[iris$Species,]
```


```{r,eval=FALSE, fig.height=3, fig.width=3}
library(tidygraph)
library(ggraph)
library(tidyverse)
DAG <- as_tbl_graph(as_array(dag))
DAG |>
  mutate(name=row_number()) |>
  ggraph() +
  geom_edge_link(arrow = arrow(angle = 10,type = "closed")) +
  geom_node_label(aes(label=name))

# ancestors matrix
A <- t(as.matrix(igraph::as_adjacency_matrix(igraph::connect(DAG,+Inf,mode = "out"))))>0
diag(A) <- TRUE
A+0
```


```{r}
# loss weights
balance_dag_weight <- function(dag,y) {
  y <- torch_tensor(y)
  w <- y$to(torch_float())$mean(1L)*torch_ones_like(y)
  w2 <- w$index_select(-1L,dag[,2L]) # weight of the childs
  y2 <- y$index_select(-1L,dag[,2L]) # label of the childs
  Z <- torch_zeros_like(y,torch_float())
  W <- Z$index_add(-1L,dag[,1L],w2) - Z$index_add(-1L,dag[,1L],y2*w2)
  W
}
W <- balance_dag_weight(dag,y)
```


```{r fit,message=FALSE, include=FALSE}
m <- nn_linear |>
  setup(loss=nn_dag_loss(dag,W),optimizer = optim_adam) |>
  set_hparams(in_features=4,out_features=ncol(y)) |>
  set_opt_hparams(lr=.5) |>
  fit(data=list(x,y),accelerator=accelerator(cpu=TRUE),epoch=500,dataloader_options=list(batch_size=200,drop_last=FALSE))
```


```{r}
p <- predict(m,x,accelerator = accelerator(cpu=TRUE))
heatmap(as_array(p),Rowv = NA,Colv = NA,col=colorRampPalette(c("white","black"))(11))
table(
  c(3,5)[max.col(as_array(p)[,c(3,5)])],
  max.col(as_array(p)[,c(1,2)]),
  iris$Species
)
table(iris$Species,max.col(as_array(p)[,1:3]))
```




